# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
   { device = "/dev/disk/by-uuid/80ba2cc8-fd55-4164-99af-e576b5f4335e";
       fsType = "ext4";
     };

  fileSystems."/boot" =
     { device = "/dev/disk/by-uuid/D745-9DEC";
       fsType = "vfat";
     };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2a91ae12-e3f7-48a9-b596-c6c89c4d7d57"; }
    ];

  fileSystems."/home/azurice/Files" =
    { device = "/dev/disk/by-uuid/2CA0167BA0164C28";
      fsType = "ntfs";
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
